#################################################################################################
######      lecture des valeurs du GTN-100024v via esphome avec clonage fonction Ecran 
#################################################################################

substitutions:
  #############################
  # comomon substitution #####
  ############################  
  
  name: Gtn-1000-24v-displaypro
  esphome_name: "gtn-1000-24v-diplay-esp"
  friendly_name: "Gtn-1000-24v"
  sensor_prefix: "gtn1000display"
  device_description: "Monitor and control the Soyosource GTN (Display version) via the display port and control the power output on demand via RS485"
  external_components_source: github://syssi/esphome-soyosource-gtn-virtual-meter@main
  # The internal display port should be connected to these GPIOs using a JST XH 2.54mm, 4 Pin connector (RX, TX, GND, VCC) USB Header (GND black, RX green, TX white, 5V red)
  # A optocoupler / optical isolator (f.e. ADUM1201) between the display port and the ESP is recommended if the ESP isn't powered by the display port!
  time_timezone: "Europe/Paris"
  projectname: "Pat.GTN100024VDisplay Virtual Meter"
  appversion: 2.1.0
  log_level: "INFO"
  baud_ratelog: "0"
  api_encryption_key: !secret gtn100024vdispkey
  ota_pswd: !secret gtn100024vota
  ap_pwd: !secret gtn100024vap
  adress_ip: !secret ip_gtn100024vdisp
  gateway_ip: !secret ip_gateway
  dns_ip: !secret ip_dns
  time_platform: homeassistant
  time_id: ha_time
  
  ###########################
  ## LOCAL substitution #####
  ###########################
  tx_pin_ttl_wifi: GPIO12
  rx_pin_ttl_wifi: GPIO13
  tx_pin_rs485: GPIO16
  rx_pin_rs485: GPIO5
  
status_led:
  pin: GPIO2
  
###############################
### definition de la carte ESP
###############################
esp8266:
  board: d1_mini

###################################
### inclusion de la partie commune 
###################################

<<: !include .common.yaml

##########################
##  composants externes ##
##########################

external_components:
  - source: ${external_components_source}
    refresh: 0s


#########
# UART ##
#########

uart:
  - id: uart_0
    baud_rate: 9600
    tx_pin: ${tx_pin_ttl_wifi}
    rx_pin: ${rx_pin_ttl_wifi}

  - id: uart_1
    baud_rate: 4800
    tx_pin: ${tx_pin_rs485}
    rx_pin: ${rx_pin_rs485}

soyosource_modbus:
  - id: modbus0
    uart_id: uart_1
    # flow_control_pin: GPIO12

    # Optional settings
    #
    # The name is used as prefix for some log messages and should
    # help to distinguish between different instances/devices
    name: soyo01_inverter

soyosource_virtual_meter:
  - id: virtualmeter0
    soyosource_modbus_id: modbus0

    # The state of this sensor (instantaneous power in watt) is used as source
    power_id: powermeter0

    # Optional settings
    power_sensor_inactivity_timeout: 20s
    power_demand_calculation: NEGATIVE_MEASUREMENTS_REQUIRED
    min_power_demand: 0
    max_power_demand: 900
    zero_output_on_min_power_demand: true
    # Split/distribute the power demand if you have multiple inverters attached to the same RS485 bus
    power_demand_divider: 1
    # A positive buffer value (10) tries to avoid exporting power to the grid (demand - 10 watts)
    # A negative buffer value (-10) exports power to the grid (demand + 10 watts)
    buffer: 10
    # The operation_status_id sensor is expected here. Passing the operation_status won't work
    # The state is used to suspend the limiter if the operation status of the inverter isn't 0x0 (normal)
    operation_status_id: operation_status_id0

    # The update interval is important and defaults to 3 seconds. If the demand is sent too frequently
    # or rarely the interverter stops. TODO: Identify and validate the lower and upper update limit
    update_interval: 3s

soyosource_display:
  - id: display0
    uart_id: uart_0
    protocol_version: SOYOSOURCE_DISPLAY_VERSION
    update_interval: 5s

binary_sensor:
  - platform: soyosource_display
    fan_running:
      name: "${name} fan running"
    limiter_connected:
      name: "${name} limiter connected"

button:
  - platform: soyosource_display
    restart:
      name: "${name} restart"

number:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    buffer:
      name: "${name} buffer"
      initial_value: 10
      restore_value: true
    manual_power_demand:
      name: "${name} manual power demand"
      max_value: 600
    max_power_demand:
      name: "${name} max power demand"
      initial_value: 295
      max_value: 600
      restore_value: true
    power_demand_divider:
      name: "${name} power demand divider"
      initial_value: 1
      restore_value: true

  - platform: soyosource_display
    start_voltage:
      name: "${name} start voltage"
    shutdown_voltage:
      name: "${name} shutdown voltage"
    # Maximum output power in limiter mode / Output power in constant power mode
    output_power_limit:
      name: "${name} output power limit"
    start_delay:
      name: "${name} start delay"

select:
  - platform: soyosource_display
    operation_mode:
      name: "${name} operation mode"
      optionsmap:
        1: "Battery Constant Power"
        2: "PV"
        16: "Battery Limit"

sensor:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    power_demand:
      name: "${name} power demand"

  - platform: soyosource_display
    error_bitmask:
      name: "${name} error bitmask"
    operation_mode_id:
      name: "${name} operation mode id"
    operation_status_id:
      name: "${name} operation status id"
      id: operation_status_id0
    battery_voltage:
      name: "${name} battery voltage"
    battery_current:
      name: "${name} battery current"
    battery_power:
      name: "${name} battery power"
    ac_voltage:
      name: "${name} ac voltage"
    ac_frequency:
      name: "${name} ac frequency"
    temperature:
      name: "${name} temperature"
    output_power:
      name: "${name} output power"

#   # import smartmeter reading from homeassistant
#   # requires the "api" component see above
  - platform: homeassistant
    id: powermeter0
    name: "${name} smartmeter instantaneous power"
    entity_id: cptlinky_power
    # filters:
    #   - throttle_average: 15s

switch:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    manual_mode:
      name: "${name} manual mode"
      restore_mode: RESTORE_DEFAULT_ON
    emergency_power_off:
      name: "${name} emergency power off"
      restore_mode: RESTORE_DEFAULT_OFF

text_sensor:
  - platform: soyosource_virtual_meter
    soyosource_virtual_meter_id: virtualmeter0
    operation_mode:
      name: "${name} limiter operation mode"

  - platform: soyosource_display
    errors:
      name: "${name} errors"
    operation_mode:
      name: "${name} operation mode"
    operation_status:
      name: "${name} operation status"
    